version: '{build}'

skip_non_tags: true

image: Visual Studio 2017

configuration:

- Debug

- Release

- Release_d

- Release_pp

- Release_ps

platform: x64

before_build:

- cmd: 'echo #define BUILD_VERSION_NAME L"d912pxy version: %APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_NUMBER%"  > d912pxy\build_version.h'

build:

  project: d912pxy.sln

  parallel: true

  verbosity: normal

artifacts:

- path: bin

  name: d912pxy